"""Tests for backtest API endpoints using FastAPI TestClient.

All external dependencies (engine, repository) are mocked.
"""

import asyncio
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.modules.backtest.api import router as backtest_router


@pytest.fixture
def app():
    """Create a minimal FastAPI app with the backtest router."""
    app = FastAPI()
    app.include_router(backtest_router, prefix="/api/v1/backtest")
    return app


@pytest.fixture
def client(app):
    return TestClient(app)


@pytest.fixture(autouse=True)
def clear_state():
    """Ensure in-memory state is clean between tests."""
    from app.modules.backtest import api
    if hasattr(api, "_runs"):
        api._runs.clear()
    yield
    if hasattr(api, "_runs"):
        api._runs.clear()


def _valid_config() -> dict:
    return {
        "start_date": "2024-01-02",
        "end_date": "2024-06-28",
        "initial_capital": 1_000_000,
        "rebalance_frequency": "weekly",
        "branch_name": "growth",
        "use_llm_agents": False,
    }


# ---------------------------------------------------------------------------
# POST /run
# ---------------------------------------------------------------------------


class TestPostRun:
    @patch("app.modules.backtest.api._run_backtest_background", new_callable=AsyncMock)
    def test_returns_202_with_running_status(self, mock_bg, client):
        """POST /run returns 202 with status 'running' — engine runs in background."""
        response = client.post("/api/v1/backtest/run", json=_valid_config())
        assert response.status_code == 202
        data = response.json()
        assert data["status"] == "running"

    @patch("app.modules.backtest.api._run_backtest_background", new_callable=AsyncMock)
    def test_backtest_id_is_handler_generated_uuid(self, mock_bg, client):
        """backtest_id should be a UUID generated by the handler."""
        response = client.post("/api/v1/backtest/run", json=_valid_config())
        data = response.json()
        # Should be a valid UUID format (36 chars with dashes)
        assert len(data["backtest_id"]) == 36

    @patch("app.modules.backtest.api._run_backtest_background", new_callable=AsyncMock)
    def test_creates_run_record(self, mock_bg, client):
        """POST /run should create a BacktestRunRecord in _runs."""
        from app.modules.backtest.api import _runs
        response = client.post("/api/v1/backtest/run", json=_valid_config())
        backtest_id = response.json()["backtest_id"]
        assert backtest_id in _runs
        assert _runs[backtest_id].status == "running"

    @patch("app.modules.backtest.api._run_backtest_background", new_callable=AsyncMock)
    def test_enqueues_background_task(self, mock_bg, client):
        """POST /run should enqueue _run_backtest_background via BackgroundTasks."""
        response = client.post("/api/v1/backtest/run", json=_valid_config())
        backtest_id = response.json()["backtest_id"]
        mock_bg.assert_called_once()
        assert mock_bg.call_args[0][0] == backtest_id

    def test_invalid_config_returns_422(self, client):
        """Missing required fields should return validation error."""
        response = client.post("/api/v1/backtest/run", json={"start_date": "2024-01-02"})
        assert response.status_code == 422


# ---------------------------------------------------------------------------
# POST /estimate
# ---------------------------------------------------------------------------


class TestPostEstimate:
    @patch("app.modules.backtest.api.estimate_cost")
    def test_returns_cost_breakdown(self, mock_estimate, client):
        mock_estimate.return_value = {
            "estimated_rebalances": 26,
            "estimated_llm_calls": 0,
            "estimated_cost_usd": 0.0,
            "estimated_duration_minutes": 2.0,
        }
        response = client.post("/api/v1/backtest/estimate", json=_valid_config())
        assert response.status_code == 200
        data = response.json()
        assert "estimated_rebalances" in data

    @patch("app.modules.backtest.api.estimate_cost")
    def test_quantitative_mode_zero_llm_calls(self, mock_estimate, client):
        mock_estimate.return_value = {
            "estimated_rebalances": 26,
            "estimated_llm_calls": 0,
            "estimated_cost_usd": 0.0,
            "estimated_duration_minutes": 2.0,
        }
        config = _valid_config()
        config["use_llm_agents"] = False
        response = client.post("/api/v1/backtest/estimate", json=config)
        assert response.json()["estimated_llm_calls"] == 0


# ---------------------------------------------------------------------------
# GET /{backtest_id}
# ---------------------------------------------------------------------------


class TestGetBacktest:
    @patch("app.modules.backtest.api.get_backtest_result")
    def test_returns_full_result_when_completed(self, mock_get, client):
        mock_get.return_value = {
            "backtest_id": "test-123",
            "status": "completed",
            "metrics": {"total_return": 0.15},
        }
        response = client.get("/api/v1/backtest/test-123")
        assert response.status_code == 200
        assert response.json()["status"] == "completed"

    @patch("app.modules.backtest.api.get_backtest_result")
    def test_returns_progress_when_running(self, mock_get, client):
        mock_get.return_value = {
            "backtest_id": "test-123",
            "status": "running",
            "progress": {"current_day": "2024-03-15", "pct_complete": 47.6},
        }
        response = client.get("/api/v1/backtest/test-123")
        assert response.status_code == 200
        assert response.json()["status"] == "running"

    @patch("app.modules.backtest.api.get_backtest_result")
    def test_returns_404_when_missing(self, mock_get, client):
        mock_get.return_value = None
        response = client.get("/api/v1/backtest/nonexistent")
        assert response.status_code == 404


# ---------------------------------------------------------------------------
# GET /
# ---------------------------------------------------------------------------


class TestListBacktests:
    @patch("app.modules.backtest.api.list_backtest_runs")
    def test_returns_paginated_list(self, mock_list, client):
        mock_list.return_value = {
            "runs": [],
            "total": 0,
        }
        response = client.get("/api/v1/backtest/")
        assert response.status_code == 200

    @patch("app.modules.backtest.api.list_backtest_runs")
    def test_accepts_status_filter(self, mock_list, client):
        mock_list.return_value = {"runs": [], "total": 0}
        response = client.get("/api/v1/backtest/?status=completed")
        assert response.status_code == 200
        mock_list.assert_called_once()


# ---------------------------------------------------------------------------
# POST /{backtest_id}/cancel
# ---------------------------------------------------------------------------


class TestCancelBacktest:
    @patch("app.modules.backtest.api.cancel_backtest")
    def test_cancel_returns_200(self, mock_cancel, client):
        mock_cancel.return_value = {"status": "cancelled"}
        response = client.post("/api/v1/backtest/test-123/cancel")
        assert response.status_code == 200

    @patch("app.modules.backtest.api.cancel_backtest")
    def test_cancel_404_for_missing(self, mock_cancel, client):
        mock_cancel.side_effect = KeyError("not found")
        response = client.post("/api/v1/backtest/nonexistent/cancel")
        assert response.status_code == 404

    @patch("app.modules.backtest.api.cancel_backtest")
    def test_cancel_409_for_completed(self, mock_cancel, client):
        mock_cancel.side_effect = ValueError("already completed")
        response = client.post("/api/v1/backtest/test-123/cancel")
        assert response.status_code == 409


# ---------------------------------------------------------------------------
# GET /{backtest_id}/trades and /snapshots
# ---------------------------------------------------------------------------


class TestTradesAndSnapshots:
    @patch("app.modules.backtest.api.get_backtest_trades")
    def test_get_trades_paginated(self, mock_trades, client):
        mock_trades.return_value = {"trades": [], "total": 0}
        response = client.get("/api/v1/backtest/test-123/trades?limit=10&offset=0")
        assert response.status_code == 200

    @patch("app.modules.backtest.api.get_backtest_snapshots")
    def test_get_snapshots_paginated(self, mock_snapshots, client):
        mock_snapshots.return_value = {"snapshots": [], "total": 0}
        response = client.get("/api/v1/backtest/test-123/snapshots?limit=10&offset=0")
        assert response.status_code == 200


# ---------------------------------------------------------------------------
# Background task DB persistence
# ---------------------------------------------------------------------------


class TestBackgroundPersistence:
    @patch("app.modules.backtest.api._persist_result", new_callable=AsyncMock)
    @patch("app.modules.backtest.context.BacktestContext.build", new_callable=AsyncMock)
    async def test_persists_result_on_success(self, mock_build, mock_persist):
        """_run_backtest_background should persist result to DB on success."""
        from app.modules.backtest.api import (
            BacktestRunRecord,
            _run_backtest_background,
            _runs,
        )
        from app.modules.backtest.config import BacktestConfig

        mock_ctx = MagicMock()
        mock_ctx.cancelled = asyncio.Event()
        mock_ctx.trading_days = []
        mock_ctx.rebalance_days = set()
        mock_ctx.trade_repo = None
        mock_ctx.effective_agents_config = None
        mock_build.return_value = mock_ctx

        config = BacktestConfig(
            start_date="2024-01-02",
            end_date="2024-06-28",
            initial_capital=1_000_000,
            rebalance_frequency="weekly",
            branch_name="growth",
            use_llm_agents=False,
        )
        _runs["test-1"] = BacktestRunRecord(
            backtest_id="test-1", status="running", config=config
        )

        await _run_backtest_background("test-1", config)

        mock_persist.assert_called_once()
        assert _runs["test-1"].status == "completed"

    @patch("app.modules.backtest.api._persist_result", new_callable=AsyncMock)
    @patch("app.modules.backtest.context.BacktestContext.build", new_callable=AsyncMock)
    async def test_still_succeeds_if_persistence_fails(self, mock_build, mock_persist):
        """In-memory record should be valid even if DB persistence fails."""
        from app.modules.backtest.api import (
            BacktestRunRecord,
            _run_backtest_background,
            _runs,
        )
        from app.modules.backtest.config import BacktestConfig

        mock_ctx = MagicMock()
        mock_ctx.cancelled = asyncio.Event()
        mock_ctx.trading_days = []
        mock_ctx.rebalance_days = set()
        mock_ctx.trade_repo = None
        mock_ctx.effective_agents_config = None
        mock_build.return_value = mock_ctx
        mock_persist.side_effect = RuntimeError("DB connection lost")

        config = BacktestConfig(
            start_date="2024-01-02",
            end_date="2024-06-28",
            initial_capital=1_000_000,
            rebalance_frequency="weekly",
            branch_name="growth",
            use_llm_agents=False,
        )
        _runs["test-2"] = BacktestRunRecord(
            backtest_id="test-2", status="running", config=config
        )

        await _run_backtest_background("test-2", config)

        # In-memory record should still be valid despite DB failure
        assert _runs["test-2"].status == "completed"
        assert _runs["test-2"].result is not None


# ---------------------------------------------------------------------------
# Crash recovery startup hook
# ---------------------------------------------------------------------------


class TestCrashRecovery:
    @patch("app.modules.backtest.api.PostgresBacktestRepository")
    @patch("app.modules.backtest.api.async_session_factory")
    async def test_recover_stale_backtests_calls_mark_stale(self, mock_factory, mock_repo_cls):
        """recover_stale_backtests should create a session and call mark_stale_runs_failed."""
        from app.modules.backtest.api import recover_stale_backtests

        # session.begin() returns an async context manager
        mock_begin = MagicMock()
        mock_begin.__aenter__ = AsyncMock(return_value=None)
        mock_begin.__aexit__ = AsyncMock(return_value=False)

        mock_session = MagicMock()
        mock_session.begin.return_value = mock_begin

        # async_session_factory() returns an async context manager yielding the session
        mock_cm = MagicMock()
        mock_cm.__aenter__ = AsyncMock(return_value=mock_session)
        mock_cm.__aexit__ = AsyncMock(return_value=False)
        mock_factory.return_value = mock_cm

        mock_repo = AsyncMock()
        mock_repo.mark_stale_runs_failed = AsyncMock(return_value=3)
        mock_repo_cls.return_value = mock_repo

        count = await recover_stale_backtests()

        assert count == 3
        mock_repo.mark_stale_runs_failed.assert_called_once()

    @patch("app.modules.backtest.api.async_session_factory")
    async def test_recover_stale_backtests_returns_zero_on_db_error(self, mock_factory):
        """Should swallow DB errors and return 0 (best-effort)."""
        from app.modules.backtest.api import recover_stale_backtests

        mock_factory.side_effect = RuntimeError("DB down")

        count = await recover_stale_backtests()
        assert count == 0


# ---------------------------------------------------------------------------
# POST /screening
# ---------------------------------------------------------------------------


class TestPostScreening:
    @patch("app.modules.backtest.api.run_vectorized_screening")
    def test_returns_200_with_snapshots(self, mock_run, client):
        mock_run.return_value = {"snapshots": [], "total": 0}
        response = client.post(
            "/api/v1/backtest/screening",
            json={
                "start_date": "2024-01-02",
                "end_date": "2024-06-28",
                "branch_name": "growth",
                "step_days": 5,
            },
        )
        assert response.status_code == 200
        assert "snapshots" in response.json()

    @patch("app.modules.backtest.api.run_vectorized_screening")
    def test_passes_config_to_handler(self, mock_run, client):
        mock_run.return_value = {"snapshots": [], "total": 0}
        client.post(
            "/api/v1/backtest/screening",
            json={
                "start_date": "2024-01-02",
                "end_date": "2024-06-28",
                "branch_name": "growth",
                "step_days": 10,
            },
        )
        mock_run.assert_called_once()
