"""Initial schema - all Phase 1 tables

Revision ID: 4bfc423a0705
Revises:
Create Date: 2026-02-19 10:06:42.263759

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4bfc423a0705"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("branch_id", sa.String(length=100), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_events_branch", "events", ["branch_id"], unique=False)
    op.create_index(
        "idx_events_correlation",
        "events",
        ["correlation_id"],
        unique=False,
        postgresql_where="correlation_id IS NOT NULL",
    )
    op.create_index("idx_events_created", "events", ["created_at"], unique=False)
    op.create_index("idx_events_type", "events", ["event_type"], unique=False)
    op.create_index("idx_events_type_branch_created", "events", ["event_type", "branch_id", "created_at"], unique=False)
    op.create_table(
        "funds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("total_aum", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("execution_mode", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("asset_class", sa.String(length=50), nullable=False),
        sa.Column("exchange", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "asset_class", "exchange", name="uq_instruments_symbol_class_exchange"),
    )
    op.create_index("idx_instruments_asset_class", "instruments", ["asset_class"], unique=False)
    op.create_index("idx_instruments_symbol", "instruments", ["symbol"], unique=False)
    op.create_table(
        "risk_alerts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("current_value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("action_required", sa.Text(), nullable=True),
        sa.Column("affected_branches", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_risk_alerts_level", "risk_alerts", ["level"], unique=False)
    op.create_index("idx_risk_alerts_resolved", "risk_alerts", ["resolved"], unique=False)
    op.create_table(
        "allocation_directives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fund_id", sa.UUID(), nullable=False),
        sa.Column("total_aum", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("regime", sa.String(length=50), nullable=True),
        sa.Column("allocations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fund_id"],
            ["funds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_allocations_fund", "allocation_directives", ["fund_id"], unique=False)
    op.create_index("idx_allocations_issued", "allocation_directives", ["issued_at"], unique=False)
    op.create_table(
        "branches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fund_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("branch_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("allocated_capital", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("execution_cadence", sa.String(length=50), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fund_id"],
            ["funds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("side", sa.String(length=20), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("time_in_force", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("filled_quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("average_fill_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("commission", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("agent_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_orders_branch", "orders", ["branch_id"], unique=False)
    op.create_index("idx_orders_created", "orders", ["created_at"], unique=False)
    op.create_index("idx_orders_status", "orders", ["status"], unique=False)
    op.create_table(
        "portfolios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("cash", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("margin_requirement", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("margin_used", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("nav", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_long_exposure", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_short_exposure", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id"),
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("cash", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("nav", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_long_exposure", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_short_exposure", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("gross_exposure", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("net_exposure", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("margin_used", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("position_count", sa.Integer(), nullable=False),
        sa.Column("positions_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_snapshots_at", "portfolio_snapshots", ["snapshot_at"], unique=False)
    op.create_index("idx_snapshots_branch", "portfolio_snapshots", ["branch_id"], unique=False)
    op.create_index("idx_snapshots_portfolio", "portfolio_snapshots", ["portfolio_id"], unique=False)
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("long_quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("long_cost_basis", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("short_quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("short_cost_basis", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("short_margin_used", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("realized_pnl_long", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("realized_pnl_short", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("portfolio_id", "instrument_id", name="uq_positions_portfolio_instrument"),
    )
    op.create_index("idx_positions_portfolio", "positions", ["portfolio_id"], unique=False)
    op.create_index("idx_positions_symbol", "positions", ["symbol"], unique=False)
    op.create_table(
        "trades",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("side", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("commission", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("slippage", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("execution_mode", sa.String(length=10), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_trades_branch", "trades", ["branch_id"], unique=False)
    op.create_index("idx_trades_executed", "trades", ["executed_at"], unique=False)
    op.create_index("idx_trades_order", "trades", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_trades_order", table_name="trades")
    op.drop_index("idx_trades_executed", table_name="trades")
    op.drop_index("idx_trades_branch", table_name="trades")
    op.drop_table("trades")
    op.drop_index("idx_positions_symbol", table_name="positions")
    op.drop_index("idx_positions_portfolio", table_name="positions")
    op.drop_table("positions")
    op.drop_index("idx_snapshots_portfolio", table_name="portfolio_snapshots")
    op.drop_index("idx_snapshots_branch", table_name="portfolio_snapshots")
    op.drop_index("idx_snapshots_at", table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_table("portfolios")
    op.drop_index("idx_orders_status", table_name="orders")
    op.drop_index("idx_orders_created", table_name="orders")
    op.drop_index("idx_orders_branch", table_name="orders")
    op.drop_table("orders")
    op.drop_table("branches")
    op.drop_index("idx_allocations_issued", table_name="allocation_directives")
    op.drop_index("idx_allocations_fund", table_name="allocation_directives")
    op.drop_table("allocation_directives")
    op.drop_index("idx_risk_alerts_resolved", table_name="risk_alerts")
    op.drop_index("idx_risk_alerts_level", table_name="risk_alerts")
    op.drop_table("risk_alerts")
    op.drop_index("idx_instruments_symbol", table_name="instruments")
    op.drop_index("idx_instruments_asset_class", table_name="instruments")
    op.drop_table("instruments")
    op.drop_table("funds")
    op.drop_index("idx_events_type_branch_created", table_name="events")
    op.drop_index("idx_events_type", table_name="events")
    op.drop_index("idx_events_created", table_name="events")
    op.drop_index("idx_events_correlation", table_name="events", postgresql_where="correlation_id IS NOT NULL")
    op.drop_index("idx_events_branch", table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
