"""add pipeline runs

Revision ID: 5c8e7c02dde9
Revises: 818060af929b
Create Date: 2026-04-23 16:59:15.574321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c8e7c02dde9'
down_revision: Union[str, None] = '818060af929b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_pipeline_runs_branch_date', 'pipeline_runs', ['branch_id', 'run_date'], unique=False)
    op.create_index('idx_pipeline_runs_status', 'pipeline_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pipeline_runs_status', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_branch_date', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
