"""add backtest tables

Revision ID: 818060af929b
Revises: bcb1f242b9fd
Create Date: 2026-03-04 10:04:43.774529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '818060af929b'
down_revision: Union[str, None] = 'bcb1f242b9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('equities_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('benchmark', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rebalance_count', sa.Integer(), nullable=False),
    sa.Column('total_pipeline_runs', sa.Integer(), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_runs_created', 'backtest_runs', ['created_at'], unique=False)
    op.create_index('idx_backtest_runs_status', 'backtest_runs', ['status'], unique=False)
    op.create_table('backtest_rebalance_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('rebalance_date', sa.Date(), nullable=False),
    sa.Column('screened_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('composite_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('orders_generated', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_rebalance_date', 'backtest_rebalance_details', ['rebalance_date'], unique=False)
    op.create_index('idx_backtest_rebalance_run', 'backtest_rebalance_details', ['backtest_run_id'], unique=False)
    op.create_table('backtest_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_long_exposure', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_short_exposure', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('position_count', sa.Integer(), nullable=False),
    sa.Column('positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('daily_return', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('cumulative_return', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_snapshots_date', 'backtest_snapshots', ['snapshot_date'], unique=False)
    op.create_index('idx_backtest_snapshots_run', 'backtest_snapshots', ['backtest_run_id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_trades_date', 'backtest_trades', ['trade_date'], unique=False)
    op.create_index('idx_backtest_trades_run', 'backtest_trades', ['backtest_run_id'], unique=False)
    op.create_index('idx_backtest_trades_symbol', 'backtest_trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_backtest_trades_symbol', table_name='backtest_trades')
    op.drop_index('idx_backtest_trades_run', table_name='backtest_trades')
    op.drop_index('idx_backtest_trades_date', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index('idx_backtest_snapshots_run', table_name='backtest_snapshots')
    op.drop_index('idx_backtest_snapshots_date', table_name='backtest_snapshots')
    op.drop_table('backtest_snapshots')
    op.drop_index('idx_backtest_rebalance_run', table_name='backtest_rebalance_details')
    op.drop_index('idx_backtest_rebalance_date', table_name='backtest_rebalance_details')
    op.drop_table('backtest_rebalance_details')
    op.drop_index('idx_backtest_runs_status', table_name='backtest_runs')
    op.drop_index('idx_backtest_runs_created', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
