"""add sector industry country to instruments

Revision ID: bcb1f242b9fd
Revises: e1e4e618543c
Create Date: 2026-02-26 11:41:24.889252

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bcb1f242b9fd'
down_revision: str | None = 'e1e4e618543c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('instruments', sa.Column('industry', sa.String(length=200), nullable=True))
    op.add_column('instruments', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'country')
    op.drop_column('instruments', 'industry')
    op.drop_column('instruments', 'sector')
    # ### end Alembic commands ###
