"""add equities branch tables

Revision ID: e1e4e618543c
Revises: 4bfc423a0705
Create Date: 2026-02-23 12:08:07.707574

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e1e4e618543c"
down_revision: str | None = "4bfc423a0705"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screening_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("branch_name", sa.String(length=20), nullable=False),
        sa.Column("run_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("universe_count", sa.Integer(), nullable=False),
        sa.Column("passed_count", sa.Integer(), nullable=False),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("passed_symbols", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_screening_runs_branch", "screening_runs", ["branch_id", "run_date"], unique=False)
    op.create_table(
        "agent_signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("screening_run_id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("analyst_type", sa.String(length=20), nullable=False),
        sa.Column("bullish_score", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["screening_run_id"],
            ["screening_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_agent_signals_run", "agent_signals", ["screening_run_id"], unique=False)
    op.create_table(
        "portfolio_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("screening_run_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("branch_name", sa.String(length=20), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_holdings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("current_holdings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("orders_generated", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("composite_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["screening_run_id"],
            ["screening_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_portfolio_decisions_branch", "portfolio_decisions", ["branch_id", "decided_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_portfolio_decisions_branch", table_name="portfolio_decisions")
    op.drop_table("portfolio_decisions")
    op.drop_index("idx_agent_signals_run", table_name="agent_signals")
    op.drop_table("agent_signals")
    op.drop_index("idx_screening_runs_branch", table_name="screening_runs")
    op.drop_table("screening_runs")
    # ### end Alembic commands ###
